# Site settings
title: Data Formula
name: Haoran Cai
email: haoran@uw.edu
description: > # this means to ignore newlines until "baseurl:"
   Stochastic thoughts in machine learning, statistics and programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Richard_Seattle
github_username:  everglory99

# Build settings
markdown: kramdown
